include: package:flutter_lints/flutter.yaml

linter:
  rules:
    omit_local_variable_types: false
    constant_identifier_names: false
    non_constant_identifier_names: false

analyzer:
  plugins:
    - custom_lint
  errors:
    invalid_annotation_target: ignore  
